ansible_become_pass: ENC[AES256_GCM,data:g92gOewS0PY=,iv:4/9dHY9lnyj1E24rI9GLA3V3+gUGzTVEoyOc/anRngM=,tag:AfNvl1acckcggOxOsloirQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OXQyb3E1ZnlMQXQ0K0RB
            Y2VkaEI2ZUdXMVZadXpYUnNyVGNoaE84Y0FrCmJoczJNdUg3eTQyaDNQZ3NhMWx3
            clFsVVA2QmpTejlsWEpUbUpXMFJ2M2MKLS0tIE5pek5TbEszQWo3R3FPdEdIZUhP
            d1JGblEzbUh5MGljSVZUUmMzNEdOcHMKEOVWdKbR0eZWKpqabywtBlhrz1sZKkxm
            dB3FBt52Wtio3eGg2uq047O4pN/f9PBeY0J01FmvNR5KtJjepWvpqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T13:55:46Z"
    mac: ENC[AES256_GCM,data:3CySoZM8Jl9IOxtkH0YbdTMhfXxeo92xG9CQRk4WzXM7L8n0Ut1/5Ua8+MpiswYLR2ppoH7ZDASx7zhikyin95Whjmy4CW8JSpfQmAcjS9xuBqnupTou57etDP2FR8xrfUeThbx+QcmbOpFgt1jzaqmam62Zl35dNdvf3rVGngM=,iv:MGclwZ1jh5fzHSYHcanIPbrdKWOrWPz75XGFkbwSTVc=,tag:Xjuwlww1LmlnTZLc7W7Y5g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
