ansible_become_pass: ENC[AES256_GCM,data:+cZ41O7nue8=,iv:vk3y+jdMEgamdmDHKIzkxj3B+d++xE+S9wH0zkGmFPM=,tag:WenhhdcuG/zVmkjXj0G0hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEa00xZHNVZkZSdExTT1VY
            WTdYazEycVFwbG9VRXJCN2hyU3pITG1xcVZZCjQwVjBrb1dBRUNKUkZqenluaTJt
            YkY3bjhDZ2hnNUtWeU0rUFpTck9OQkUKLS0tIHY5YTRHcXhwckRGRkN5WCtPSFNF
            NndKN0pZd0pWWGRyMFdlTnZkaStSWXMKkvEodHARyNFUs1o5JUExbvDLj1dQ0vQM
            zzpifCfdPUunv+HLQI5KBqDGdCKRtB9E5pLk/lQrtvkMObgAQfvitg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T18:50:37Z"
    mac: ENC[AES256_GCM,data:bUnDkAjUzDnhfHYUc73Sl590d6rS4jkYZptXEfG6acVgia9vHtvaQr2hv3mjr8+RTPDba1Tb+sBbJUMvHCxGjnJebCk8TQhDevCQnnxbXqqhqdiAA+PAXZBz2+exFqqGOGJdaY7ov3PDrdceRJXh1tNGXz/FV3koJeoWiW/WuHo=,iv:bwqf8elsBzZImAKDANRvYWrQ8VZ865IKjqikh6Ph5jY=,tag:IGgeyMbFwZRCnixI7Pbe+g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
