ansible_become_pass: ENC[AES256_GCM,data:ekuQxIVXrhw=,iv:1qQCgg7zTBNf3Wl8hTtr4Us5ix93tvQtGhEdhr3p0cg=,tag:e9r8b24o/ugJqbc+cK3j3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WVFZMmF3VlE1cm9mUU4r
            WWJEZEhJOFZuVmwyN21kRmI2cjdUdzZ1VUVvCklpMTArZi9jaTRONDh2cFdOOTRy
            MEpnTGFZMVZwa0srbVFScm0zM1lyWHcKLS0tIEduMTNNM1Jjb1pLUk5pM1JLODZw
            eVRIL24rVjFxSDQ3aU1oMkRJNWFKYkUKydfZerFKx4CZAAWLVOA8nD2rp1qQkak7
            J5k+btjxOcbJr9RZCKoU3hrFoN6+y7mYs4l2XxjXbbBlt5rjV61H1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T13:55:44Z"
    mac: ENC[AES256_GCM,data:dPb+/h0glrH/xAU2k3WFKeLs7crrRBzDMNwPSYfjKhd2r9ClLVqnJUhHMlm33B5CewxqvrzRvkZR9ipeGRqueYxWaCdIK8Q/jFMa9UlUsZxSnjHBb06C3LcWe+7Pbs5L8b1RVBz66kojDD47sRc/Vvrnzwyp/S/Cqwuq+TjZsRM=,iv:JY+mx9bJQ2NSUKYYKAeD5CA6GSXI2PDT/9KaBs0myVA=,tag:ISVDFO92o4Vbp9eqCpeiJg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
