apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:wbcNWWETB7c=,iv:ckbfpG/uaWDiC137/o1il4HhkgzAJYb6Wv9VVIWM/EM=,tag:dLX4M+h3jcNf6o4J0oFt1A==,type:str]
    admin-user: ENC[AES256_GCM,data:JXRsOj8=,iv:8Vzu8NSHeATUXuOlKREKpdTX1xllt0iLSn+p50udu2o=,tag:BaIPoCAtF63LvCV5zndw4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeVFFbC9LWGdBZ2k3N1VZ
            U09Jc1ZPdWE3cGZ6VWJtdWtFcUNpUW1wYXd3CkpqcU5qTWJLeThKb2I1UlMrNVVD
            UTBvakZtbmZrQktUZjN4eDM2L1ZGb1kKLS0tIFowVGJwTndNbm5zbEc0V3l6cm1l
            SXBTS1A2VWdLbFg2SGcvd3RabGl3N2MKbxLQ9rgsU7abDVWiFjPDHwHS/fZ6p2G5
            4FFR6ICnfd8eOk5KLphxmkPnwYK1lSZioLWgKQ1arovncHeqI3zCMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T18:51:59Z"
    mac: ENC[AES256_GCM,data:a8ymf61WZAaSuFY8NGWr+AkVddRSBBd4IwqxjiyxS9dRfF7ggi3dAw28h+YSvvNtk8Q5lVE3OSXa0PvO3RI3cLxo1AWo7VXfhIUSzvPa+Ycj5q2CAHuzk2mg1RGy8E5zvlVTRGeAFht9lhzzgCIi6rkXA85WG4ZN0BQxCGPBHBE=,iv:oUMC0frERKEzbkU38rQW+N9rRgXdUSjYBGcakN4REh0=,tag:VrOaG0D6IjbNDVvGajD/8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
