---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
# dependsOn:
#   - name: ingress-nginx
#     namespace: nginx
  values:
    image:
      repository: louislam/uptime-kuma
      tag: 1.23.3
      pullPolicy: IfNotPresent
    env:
      TZ: ${TZ}

    service:
      main:
        ports:
          http:
            port: 3001

    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: robot
        hosts:
          - host: &host "status.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        mountPath: /app/data
        existingClaim: uptime-config-v1
