apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:WR/Ew8ymA5oGb3iwhdrwJw==,iv:zGApqj7KSfVWXW7stB725t7N9w9tPQoFLUDqpEby6tY=,tag:6lUiJOmDN8ZiYL14C4lxrQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ckO/jDQ4k3gsDXkA0PhFHjxipBFrrRgPL4IsPo0iUqzVGvzG,iv:8QXSMYEWaM604MRPfKxmt2BlbEaHiVy3RbXd00cGL60=,tag:uNBGSVmlFblI7ZjVvp+Rpg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:nX60QFQZHa8awOg=,iv:xty54iS3fhHi015Dx2sN8d/CLHJFanuVuJ8H+0S2atQ=,tag:EdT1JBazm0aBTBzbco6YwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSi9JdUJXaytGUjF6WTl0
            WTR2Rks3NytHSjZaQUs5YmRCYzk3cjY0Q1dNCkVRd3MvZjJOWTVXWHluQ0lSRnhJ
            R2s3WjROZ2lOajdXZ1Y2MG4rYVc0ancKLS0tIDliS0pxbGZhaGIyQlhqbmZhRmRw
            aDF1dnJTUlJUWjg1Wm43cVg5cUFaS0EK5vInxdjwZP8LN8UQbh2PvplTNj6nE9c8
            4Nvq7w75de9VgTq9xPk7flePkegnRHovYgPqMyTOej77AUrvRC1RFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-06T08:25:57Z"
    mac: ENC[AES256_GCM,data:F2ZyFahWSHH2yJAqFpgTatlm48Yj6HLOMRK1T06kNf8KQ150dI5sMAoiXzgTT3wgjsZjeHMoxCu6R3pWvhsm6r5gkAlxzEje4HfLlKZUd8V/nBQKqfVwg/RSnkGcF9HsaEc2qA8pw/9RfHfCDxKhEphGsemm2eVoD1bE9bAJhKA=,iv:Dm3KtLs+9os3/BBL+fdguGNcR1Nr24YwbA7B8alpfEU=,tag:MuxhQkLg5QUzQ9+oeLs14Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
