apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:HDxNPYRz5UBMcMhKMYL4rw==,iv:hJoyqcatVCNwXCTqB/DTb9vb9liAE2bBN1OOQyCwvh8=,tag:9A7/8JKLkUVE9hQeC393XA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Zdnys9sbWSHy0I3RViXYpr2J0XCDegZyjyuyZCIVC4xqyARF,iv:Xmu5fVGO2VedOIBgY2Gc4Dwff6refIidJAonrmZMuDQ=,tag:4RGbe2jwvvyOy3nB7Raijw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:UgCOkz4d0McJ+4k=,iv:w8rlZhb/rm2ebjtDMaZhTezHpQ1HIR5OdGGsk9Y3uLI=,tag:R0/P9Lrn6EerMkRqe5FZZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENlc3Uk1FV3hQWmM2RjNi
            ZFBiK2gzOGYwS202emFSb24xdjFnVkFvQlY4Clgyc3k3c1hrZGozNGpKRXYrdTVY
            UURqdHQ4Wm5LSHluZnpYOExFMVE3dFUKLS0tIExOVUJCZEFIRXR2TEV3NFUxVStw
            NVkvZ3AvbEE1RDFWUll2YjIzZmJhZGsK7qriNkJMWd6Ilcitz4ffaV6ucGZvZFYR
            kbxu2o6gk3/m1a9uH/bEAjKCod1xqP2FGLHguCZB1oSjVWQ9V72NKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T18:51:52Z"
    mac: ENC[AES256_GCM,data:lnqBa6fstjvyyYy3c3rNy0599GS5uCG6kNtwtAOQbT1gYnXekWpWJXoAwUGA+IOBwLPLpRMuOsc8d8f2Pv/eQjyRAjErNJRgWs8tzPb8GtctFn3lM+5LUUzfOJDq/vtuyf9263jduCOhdA/T4ZYjt2SNTKDwToch6z/j12xZwVY=,iv:jt9LGJFPY/haLPq0bN8BlMhLiOhBG2rsVujRgYU7I2s=,tag:zhxvZlqGhYQvnQEVKU08Lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
