apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:2clsOyyVFbOZBcylrxSBkg==,iv:wXgHfInTn713q6ubKnNGLxZ6LiyRsXSaWqrWPgL2WTQ=,tag:cGbBz5iFN1AJ2ym+qiORwA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:O9X/e/ZLk578vUoTB1kFEIeCEMTMxPls+s40J7ObjiA1y29Y,iv:9EQBXky9jr5+maRijKLTlzH0iHZ6hY1XZsXlPmYEsMI=,tag:9h6tvoWOlp7KqYeiJeIxcw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:firDqGkpHqcmTns=,iv:TdzvGwHFeO+6WrRhhiNLVIx//LQJhjt8jsM8elkIsuI=,tag:ZR4P9hRMboNn3uriBDnZpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTnBRS2FqekdjTDZjN1dL
            c0h1a1A1TVNXaExMNW1WL00zMWY4bDloeWs4CjViUHVEeFQ1b29rUVBjcmlSWDJC
            Y3M2aG1YbTdnd2xxUlZLb1NCU09FbUEKLS0tIEZyZ1BvbUpFeUJmZENXcFQvdHlQ
            QllsNDkydGRya3UwUk91Mm5TVE11SlUKxmZCBalJSxpnv/9aJKRFUC10FqkMHnIG
            iH2tTpyJSx6PIMQ8qDKpA88prwFh4Q6oN16x932bHmE/aNILMPOSVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T13:57:01Z"
    mac: ENC[AES256_GCM,data:+EagMskfS0f7WNeWjUVRlqbvksp3nDxRBdrZXYoTsSMTcTRdiSXoP+I5Tu+552QxGFnGeucbVexHuBvaHwVeSUtf4ydSPCa3fGmDwZHSNV8nUPwE+iA75kGJxomGSquEkR4rooUie9rEJZTy9q02VTdMlsD8DN2P5kvURL8F0o8=,iv:zMV/yI/AqM1EnwvWwfg2ksNYelaByAY1ZBKV3F4tGcE=,tag:QSxEw7H4GI+jb2NUtwpFsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
