apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:SjHqqbSrEZZpTJ3vYLGh9WImlOrDyWv39x1tpvZ1cjuWTvap,iv:8Ky4qaHap46YWr/5lqfkXB0CS046PA1wN8+gr2/QdPI=,tag:ZmSE4uLrxbNVuw7XE6VePg==,type:str]
    credentials.json: ENC[AES256_GCM,data:nF4OLBUia2b/SFWebH7jERw+Gy8MYptmDoZDp7GjGlh9vdxVhnPCMLLjKCoEIAfy6LfQ12v6k7Kad/Ad4fohGkL0PHUYJ/j604ZokKHroUOdvgeKWl75wgTINe4z0oL4mnohAQoc4qkJplsAtM6ysSlb22OJzssGT2L8PPKN1E4CkHCIFoDXNKD4ZovzJLb71hc80/nEsx3imvHTlUWuPfAVip6wOp7CbE3smQF4xw==,iv:yOMr/Oo4hleS+zlUKua15MoKPGCyZoC2/UDriQvVmN0=,tag:Ji2n47zGV4TC6v9fy6dCyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbm80V0FVVEhFSFkvRCtn
            LzZhcTRsQ0dNV29XRnpvOTB2dk13K0haUjBzCnV6VzNkUlkyTWdlOGFJbmpIbWwx
            R1hmSkM0cldtc0lna1FrYUo5QVFaUTgKLS0tIGJZUjJ1MVZ4YVJha2toNTZpUURl
            VXhmdmw2RENaNUY5ZmpuQnZBeDdFdFUKku5HCFh35nn+0H5axE6FMA9KPpIChVN+
            C9Y+4/nZGH6NtSmg9bdBrxhfnvEl2Z/2++bl19rzxqvHmX9qjDoBgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-06T06:33:06Z"
    mac: ENC[AES256_GCM,data:AAyHm5pjmAedJltimV+ekErESkeFZeeELxRWUzF1gVu8gUnuTW0entYKSNXkOXvwW/azB2cTxLbYFJdjv26v2nfY1ghi+L/S2iUPYXfqppKR6eojTmpOPcU1Br05dbWajQ0jORDgCbe8UIPc3d435DhNl1duNkR3VskhmVvkooA=,iv:AKyTirTThUxHiutBtrF8SYfj7eAj6NGjBbs6ebhjJL4=,tag:H84rNV5yOXX/8vfHMM68bA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
